package com.relink.chat.model.po;

public class GroupRelationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_relation.group_relation_id
     *
     * @mbg.generated
     */
    private Integer groupRelationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_relation.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_relation.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_relation.group_relation_id
     *
     * @return the value of group_relation.group_relation_id
     *
     * @mbg.generated
     */
    public Integer getGroupRelationId() {
        return groupRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_relation.group_relation_id
     *
     * @param groupRelationId the value for group_relation.group_relation_id
     *
     * @mbg.generated
     */
    public void setGroupRelationId(Integer groupRelationId) {
        this.groupRelationId = groupRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_relation.group_id
     *
     * @return the value of group_relation.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_relation.group_id
     *
     * @param groupId the value for group_relation.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_relation.user_id
     *
     * @return the value of group_relation.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_relation.user_id
     *
     * @param userId the value for group_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}