package com.relink.chat.model.po;

public class GroupPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_hoster
     *
     * @mbg.generated
     */
    private Integer groupHoster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_avatar
     *
     * @mbg.generated
     */
    private String groupAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_id
     *
     * @return the value of group.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_id
     *
     * @param groupId the value for group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_name
     *
     * @return the value of group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_name
     *
     * @param groupName the value for group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_hoster
     *
     * @return the value of group.group_hoster
     *
     * @mbg.generated
     */
    public Integer getGroupHoster() {
        return groupHoster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_hoster
     *
     * @param groupHoster the value for group.group_hoster
     *
     * @mbg.generated
     */
    public void setGroupHoster(Integer groupHoster) {
        this.groupHoster = groupHoster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_avatar
     *
     * @return the value of group.group_avatar
     *
     * @mbg.generated
     */
    public String getGroupAvatar() {
        return groupAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_avatar
     *
     * @param groupAvatar the value for group.group_avatar
     *
     * @mbg.generated
     */
    public void setGroupAvatar(String groupAvatar) {
        this.groupAvatar = groupAvatar == null ? null : groupAvatar.trim();
    }
}