package com.relink.chat.model.po;

public class RelationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.relation_id
     *
     * @mbg.generated
     */
    private Integer relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.hoster
     *
     * @mbg.generated
     */
    private Integer hoster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.guest
     *
     * @mbg.generated
     */
    private Integer guest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.relation_id
     *
     * @return the value of relation.relation_id
     *
     * @mbg.generated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.relation_id
     *
     * @param relationId the value for relation.relation_id
     *
     * @mbg.generated
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.hoster
     *
     * @return the value of relation.hoster
     *
     * @mbg.generated
     */
    public Integer getHoster() {
        return hoster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.hoster
     *
     * @param hoster the value for relation.hoster
     *
     * @mbg.generated
     */
    public void setHoster(Integer hoster) {
        this.hoster = hoster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.guest
     *
     * @return the value of relation.guest
     *
     * @mbg.generated
     */
    public Integer getGuest() {
        return guest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.guest
     *
     * @param guest the value for relation.guest
     *
     * @mbg.generated
     */
    public void setGuest(Integer guest) {
        this.guest = guest;
    }
}