server:
  port: 9998
spring:
  application:
    name: chatroom-user # 服务名称

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

  jms:
    pub-sub-domain: true # 发布订阅模式
    template:
      delivery-mode: persistent # 消息持久化

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/chatroom?serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000

mybatis:
  type-aliases-package: com.relink.chat.model.po
  mapper-locations: classpath*:com.relink.chat.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
