package com.relink.chat.mapper;

import com.relink.chat.model.po.GroupRelationPo;
import com.relink.chat.model.po.GroupRelationPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GroupRelationPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int deleteByExample(GroupRelationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int insert(GroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int insertSelective(GroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    List<GroupRelationPo> selectByExample(GroupRelationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    GroupRelationPo selectByPrimaryKey(Integer groupRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupRelationPo record, @Param("example") GroupRelationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupRelationPo record, @Param("example") GroupRelationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupRelationPo record);
}